/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testjni2 */

#ifndef _Included_testjni2
#define _Included_testjni2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testjni2
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_testjni2_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
